### PR TITLE
[NO MRG] Test CI

### PR DESCRIPTION
**Pull request by jakirkham**
Opening to test CI

### CODE REVIEW

**Comment by jakirkham** [comment]
Seeing this error in various forms [on CI]( https://github.com/rapidsai/pynvjitlink/actions/runs/11279298830/job/31370167586?pr=107#step:7:427 )

```
/__w/pynvjitlink/pynvjitlink/test_binary_generation /__w/pynvjitlink/pynvjitlink
GPU CC: 70
Alternative CC: 80
# Compile all test objects
nvcc -O3 -rdc true -gencode arch=compute_70,code=sm_70 --cubin -o ../pynvjitlink/tests/undefined_extern.cubin undefined_extern.cu
<command-line>: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
make: *** [Makefile:41: all] Error 1
```

Looks like we are picking up [`cuda-nvcc` version `12.4` from the `nvidia` channel]( https://github.com/rapidsai/pynvjitlink/actions/runs/11279298830/job/31370167586?pr=107#step:7:308 )

```
cuda-nvcc                 12.4.131                      0    nvidia
```

This was before important packaging fixes were ported over. Hence why `cuda-cudart` is not being pulled in by `cuda-nvcc`

**Comment by bdice** [comment]
I'm exploring strict channel priority as a potential solution in #109.

**Comment by bdice** [comment]
#109 resolved the CI issue, so this can be closed.

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

**Pull request closed without merging**
