### PR TITLE
Release 0.1.7

### PR DESCRIPTION
**Pull request by jakirkham**
* Add Conda packages and CI workflows (#33)
* Set pipefail in wheel build scripts (#34)
* [REVIEW] remove references to setup.py in docs (#36)
* Update README.md (#37)
* Remove usages of rapids-env-update (#41)

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @vyasr

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
@jakirkham Will you create the tag after merging? I’m not sure who has permissions for that. If you don’t, I can try it.

**Comment by jakirkham** [comment]
I'm happy to try

**Comment by jakirkham** [comment]
Have made a tag locally. Just trying to test it out before attempting to push

**Comment by jakirkham** [comment]
Ok have pushed the tag for [`v0.1.7`]( https://github.com/rapidsai/pynvjitlink/releases/tag/v0.1.7 )

Here are [the builds]( https://github.com/rapidsai/pynvjitlink/actions/runs/7509197488 )

**Comment by jakirkham** [comment]
Looks like the packages built ok, but not sure about the upload. It shows as passed, but see [this line]( https://github.com/rapidsai/pynvjitlink/actions/runs/7509197488/job/20446052583#step:9:18 )

```
jq: error (at <unknown>): Cannot iterate over null (null)
```

<hr>

Is there something we are missing?

AJ mentioned some changes to the `build-conda` section here ( https://github.com/rapidsai/pynvjitlink/pull/33#discussion_r1450747614 ). Though `build-wheels` didn't have those changes; whereas, both `publish-conda` and `publish-wheels` had those pieces already. Perhaps I'm misunderstanding something about that suggestion though

Are there other things we might be missing? Maybe environment variables we need?

**Comment by jakirkham** [comment]
Think `build-conda`'s `build_type` was getting set to `pull-request` when it should have been set to `branch` (like what `build-wheel` does). Fixing with PR ( https://github.com/rapidsai/pynvjitlink/pull/43 )

**Comment by jakirkham** [comment]
Looks like the `build_type` change was the missing piece

Also just noticed that there was another hard-coded version floating around in the codebase that was missed in this PR

https://github.com/rapidsai/pynvjitlink/blob/ccf668910dc28ad248fa792debe6a106dc2e30f8/pynvjitlink/VERSION#L1

We should really consolidate these into one place (or ideally none and pickup from the tag or otherwise automate). Fixing as part of PR ( https://github.com/rapidsai/pynvjitlink/pull/44 )

**Pull request merged**
