### PR TITLE
Fix pre-commit copyright check

### PR DESCRIPTION
**Pull request by bdice**
This PR is a small fix for an error I ran into locally on the copyright check.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

Should we add copyright lines to other files like these as well?

https://github.com/rapidsai/pynvjitlink/blob/571a69e68cf763b03ad407ca12589713793c2639/.ycm_extra_conf.py#L1

https://github.com/rapidsai/pynvjitlink/blob/571a69e68cf763b03ad407ca12589713793c2639/test_binary_generation/Makefile#L1

https://github.com/rapidsai/pynvjitlink/blob/571a69e68cf763b03ad407ca12589713793c2639/test_binary_generation/test_device_functions.cu#L1

https://github.com/rapidsai/pynvjitlink/blob/571a69e68cf763b03ad407ca12589713793c2639/test_binary_generation/undefined_extern.cu#L1

**Comment by bdice** [comment]
@jakirkham The copyright checker will enforce that in the future, next time those files are modified. If you would like to add them in this PR, feel free to push.

**Review by gmarkall — APPROVED** [review]

**Comment by bdice** [comment]
I'm going to merge this as-is. We can gradually fix the files in this repo as they are edited, which is the same strategy we've been using across RAPIDS.

**Pull request merged**
