### PR TITLE
Fix #39 by matching current Numba implementation of `add_cu()`

### LINKED ISSUE #39: [BUG] The Numba patch breaks some functionality for versions 0.58 and above
The Numba test suite, when run with the pynvjitlink patch, fails some tests. To run the test suite with the patch, the following script can be used:

```python
from pynvjitlink import patch
patch.patch_numba_linker()
#patch.patch_numba_for_lto()

if __name__ == '__main__':
    from numba.testing._runtests import _main
    import sys

    sys.exit(0 if _main(sys.argv) else 1)
```

invoked with

```bash
python test_patched_numba.py numba.cuda.tests -v -m
```

ends with

```
Ran 1462 tests in 134.056s

FAILED (errors=28, skipped=33, expected failures=11)
```

The errors are of this form:

```
======================================================================
ERROR: test_ex_linking_cu (numba.cuda.tests.doc_examples.test_ffi.TestFFI.test_ex_linking_cu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/doc_examples/test_ffi.py", line 42, in test_ex_linking_cu
    multiply_vectors[1, 32](r, x, y)
  File "/home/gmarkall/numbadev/numba/numba/cuda/dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/cuda/dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/cuda/dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/cuda/dispatcher.py", line 926, in compile
    kernel.bind()
  File "/home/gmarkall/numbadev/numba/numba/cuda/dispatcher.py", line 197, in bind
    self._codelibrary.get_cufunc()
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 195, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 172, in get_cubin
    linker.add_file_guess_ext(path)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2656, in add_file_guess_ext
    self.add_cu_file(path)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2648, in add_cu_file
    self.add_cu(cu, os.path.basename(path))
  File "/home/gmarkall/numbadev/nvjitlink/pynvjitlink/patch.py", line 129, in add_cu
    self.add_ptx(program.ptx.rstrip(b"\x00"), ptx_name)
                 ^^^^^^^^^^^
AttributeError: 'NvrtcProgram' object has no attribute 'ptx'

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by gmarkall**
Numba 0.58 implements `add_cu()` differently to Numba 0.57 and below. These changes bring the implementation in the patch in line with Numba 0.58 onwards, and makes the minimum supported Numba version 0.58, so that we don't have to support multiple different implementations. There is presently no widespread production use (or perhaps no production use at all) of pynvjitlink with Numba 0.57, so keeping Numba 0.57 compatibility is not considered.

Testing of the patch against the current Numba version is added to the CI configuration.

The version number is bumped to 0.1.12 to reflect the nature of this change.

Fixes #39

### CODE REVIEW

**Comment by bdice** [comment]
@gmarkall Is this PR needed for pynvjitlink to be released publicly / made a hard dependency of cudf?

**Comment by gmarkall** [comment]
@bdice It ought to go in as otherwise pynvjitlink breaks float16 support in Numba and any third-party use of .cu files (of which there are various users). I will fix this up today.

**Comment by gmarkall** [comment]
This should be ready for review now.

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
@gmarkall Can you update the PR description?

**Comment by gmarkall** [comment]
@bdice Thanks for the pointer, apologies for missing that earlier.

**Comment by jakirkham** [comment]
Added a fixes note in the OP. Hope that is ok

**Review by vyasr — APPROVED** [review]

**Review by brandon-b-miller — APPROVED** [review]

**Pull request merged**
